//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tren_yonetim.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbTrenYonetimEntities1 : DbContext
    {
        public DbTrenYonetimEntities1()
            : base("name=DbTrenYonetimEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tbl_musteri> tbl_musteri { get; set; }
        public virtual DbSet<tbl_rezervasyon> tbl_rezervasyon { get; set; }
        public virtual DbSet<tbl_saatler> tbl_saatler { get; set; }
        public virtual DbSet<tbl_tren> tbl_tren { get; set; }
        public virtual DbSet<tbl_vagon> tbl_vagon { get; set; }
    }
}
