//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tren_yonetim.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_vagon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_vagon()
        {
            this.tbl_musteri = new HashSet<tbl_musteri>();
            this.tbl_rezervasyon = new HashSet<tbl_rezervasyon>();
        }
    
        public int vagonid { get; set; }
        public string vagonad { get; set; }
        public Nullable<int> kapasite { get; set; }
        public Nullable<int> doluluk_orani { get; set; }
        public Nullable<int> trenid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_musteri> tbl_musteri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_rezervasyon> tbl_rezervasyon { get; set; }
        public virtual tbl_tren tbl_tren { get; set; }
    }
}
