//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tren_yonetim.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_rezervasyon
    {
        public int rezid { get; set; }
        public Nullable<int> rezkisisayisi { get; set; }
        public Nullable<int> musteriid { get; set; }
        public Nullable<int> vagonid { get; set; }
        public string tarih { get; set; }
    
        public virtual tbl_musteri tbl_musteri { get; set; }
        public virtual tbl_vagon tbl_vagon { get; set; }
    }
}
